// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {time} from '../models';
import {backend} from '../models';

export function CreateTask(arg1:string,arg2:time.Time,arg3:string):Promise<backend.Task>;

export function DeleteTask(arg1:number):Promise<void>;

export function GetTasks():Promise<Array<backend.Task>>;

export function UpdateTask(arg1:number,arg2:string,arg3:boolean,arg4:time.Time,arg5:string):Promise<backend.Task>;
