// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTask(arg1, arg2, arg3) {
  return window['go']['backend']['API']['CreateTask'](arg1, arg2, arg3);
}

export function DeleteTask(arg1) {
  return window['go']['backend']['API']['DeleteTask'](arg1);
}

export function GetTasks() {
  return window['go']['backend']['API']['GetTasks']();
}

export function UpdateTask(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['backend']['API']['UpdateTask'](arg1, arg2, arg3, arg4, arg5);
}
